export const LOGIN_POST = 'LOGIN_POST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_POST = 'SIGNUP_POST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const ON_CHANGES_PROPS = 'ON_CHANGES_PROPS';

export const PROFILE_GET = 'PROFILE_GET';
export const PROFILE_POST = 'PROFILE_POST';
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';
export const PROFILE_POST_SUCCESS = 'PROFILE_POST_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const BUSINESS_DETAIL_GET = 'BUSINESS_DETAIL_GET';
export const BUSINESS_DETAIL_GET_SUCCESS = 'BUSINESS_DETAIL_GET_SUCCESS';
export const BUSINESS_ADD_POST = 'BUSINESS_ADD_POST';
export const BUSINESS_EDIT_POST = 'BUSINESS_EDIT_POST';
export const BUSINESS_POST_SUCCESS = 'BUSINESS_POST_SUCCESS';
export const BUSINESS_CATEGORY_GET = 'BUSINESS_CATEGORY_GET';
export const BUSINESS_CATEGORY_GET_SUCCESS = 'BUSINESS_CATEGORY_GET_SUCCESS';
export const BUSINESS_SUBURBS_GET = 'BUSINESS_SUBURBS_GET';
export const BUSINESS_SUBURBS_GET_SUCCESS = 'BUSINESS_SUBURBS_GET_SUCCESS';
export const BUSINESS_FAIL = 'BUSINESS_FAIL';

export const OFFER_GET = 'OFFER_GET';
export const OFFER_ADD_POST = 'OFFER_ADD_POST';
export const OFFER_EDIT_POST = 'OFFER_EDIT_POST';
export const OFFER_GET_SUCCESS = 'OFFER_GET_SUCCESS';
export const OFFER_POST_SUCCESS = 'OFFER_POST_SUCCESS';
export const OFFER_MANAGE_GET = 'OFFER_MANAGE_GET';
export const OFFER_MANAGE_SUCCESS = 'OFFER_MANAGE_SUCCESS';
export const OFFER_REDEEMED_GET = 'OFFER_REDEEMED_GET';
export const OFFER_REDEEMED_SUCCESS = 'OFFER_REDEEMED_SUCCESS';
export const OFFER_FAIL = 'OFFER_FAIL';
